enum mutationTypes {
  SET_USER_INFO = 'SET_USER_INFO',
  SET_POOLS = 'SET_POOLS',
  SET_HISTORYS = 'SET_HISTORYS',
  SET_APYS = 'SET_APYS',
  SET_LOADING_POOLS = 'SET_LOADING_POOLS',
  SET_CURRENT_POOL = 'SET_CURRENT_POOL',
  SET_SHOW_WALLET_MODEL = 'SET_SHOW_WALLET_MODEL',
}
export default mutationTypes
